- api/requests/Request.php
I guess this should fix issue #43. I am not a PHP developer so please verify this little tiny change. I guess the 401 code in the `<error code="401">` response tag is loaded dynamically from this value?
> Send correct HTTP status code when missing required params

- README.md
- api/APIPost.php
- api/feedback/occupancy.php
When a GET request is done to https://irail.be/feedback/occupancy, a 405 error is returned saying that you can only do post requests.
> Add 405 when GET request to the occupancy feedback URL is done

- api/APIPost.php
- api/spitsgids/SpitsgidsController.php
This issue should be fully fixed now: https://github.com/iRail/iRail/issues/181.
> Post data pushed to the feedback and occupancy table

- api/data/NMBS/connections.php
This partly fixes #199, allowing to get NMBS connections that do not
use international trains.
I've also been playing around a bit with the idea of having some kind of `TransportType` "enum" class, like
```
class TransportType {
const TRAINS               = 0b1111111000000000;
const INTERNATIONAL_TRAINS = 0b1000000000000000;
const ALL                  = 0b1111111111111111;
}
```
that would allow to use boolean operations like `TransportType::TRAINS & !TransportType::TRAINS` as `TypeOfTransport` parameter. However I do not now how this could be mapped nicely in the API.
> Added `nointernationaltrains` type of transport option

- api/APIPost.php
- api/data/NMBS/vehicleinformation.php
- api/occupancy/OccupancyDao.php
- api/occupancy/OccupancyOperations.php
- api/requests/VehicleinformationRequest.php
This is an example of the new kind of queries that are possible: https://api.irail.be/vehicle?id=BE.NMBS.IC2414&date=260716
> Date parameter in vehicle GET request

- api/data/NMBS/vehicleinformation.php
Fixed https://github.com/iRail/iRail/issues/224.
> Connection id will be right even if the parameter has no "BE.NMBS."-prefix in the vehicle GET request

- api/APIPost.php
- api/occupancy/OccupancyDao.php
If someone gives feedback in the weekend for a train in the week, the feedback wasn't going in the database. This pull request fixes that issue (it was reported here: https://github.com/iRail/iRail/issues/244).
> Feedback in weekend for a train during the week

- api/data/NMBS/liveboard.php
Use the date passed in URL parameters when showing a liveboard, instead of the hardcoded current day. Fixes #273
> Hotfix: #273 Liveboard use the date parameter passed in the URL

- api/data/NMBS/connections.php
- api/data/NMBS/liveboard.php
- api/data/NMBS/vehicleinformation.php
Bug fix for #283.
* Strip style tags, but keep <a> tags since they might contain valuable information. 
* When printing as json, json encode the alert description.
> Hotfix: Strip alerts from style html, and use json-encode when printing json #283

- api/data/NMBS/vehicleinformation.php
NMBS Vehicle data validation should be more prone against crashes now
> Fixed check if vehicle information is available, and show an appropriate message if it's not #275

- api/data/NMBS/connections.php
- api/data/NMBS/liveboard.php
As described in issue #354, international connections aren't shown in the connections endpoint.
This PR updates the vehicle selection codes so they are identical to the requests made by the NMBS application. The location fields have been updated as well with some more parameters to stay closer to the requests made by the NMBS. The vehicle filter variable has been renamed for clearer code.
> Fix connections endpoint by updating the vehicle filter codes #354

- api/data/NMBS/connections.php
- api/data/NMBS/liveboard.php
- api/data/NMBS/stations.php
- api/data/structs.php
- api/requests/ConnectionsRequest.php
This PR implements the method discussed in #356 to automaticly determine whether or not to include high-speed trains.
When both stations are in Belgium, high speed trains are excluded unless the query explicitly states to include all traffic. This is needed as our data source will hide local trains due to faster high speed trains when searching for routes, while those high-speed trains are useless to most of the travellers
> Avoid high-speed trains when both departure and destination are in Belgium

- api/data/NMBS/Composition.php
- api/data/NMBS/Connections.php
- api/data/structs.php
This PR will add intermediary stops to journey queries. This way travellers can see how many stops their train will make before they have to get off.
> Include intermediary stops #348

- api/data/NMBS/Disturbances.php
- api/data/structs.php
When merged, this PR will add a "type" field to all disturbance objects on the /disturbances page. Possible values are 'disturbance' and 'planned'. This way scheduled work can be distinguished from unscheduled disturbances.
Fixes #393
> Add type field to disturbances

- api/data/NMBS/Connections.php
This PR improves data quality for intermediate stops data (#348). This PR ensures that both left and arrived for an intermediate stop are set to 1 (true) if the train has arrived in a later stop.
A train A->B->C which is reported as expected in A and B, but arrived in C, will be fixed to show as arrived and departed in both A and B.
> Ensure the arrived/left data for intermediate stops is sane

- api/APICall.php
- api/APIPost.php
- api/data/DataRoot.php
- api/data/NMBS/Composition.php
- api/data/NMBS/Connections.php
- api/data/NMBS/Disturbances.php
- api/data/NMBS/Liveboard.php
- api/data/NMBS/Tools.php
- api/data/NMBS/VehicleInformation.php
- api/output/Printer.php
This PR fixes a case where the routeplanner endpoint contained trains that weren't reported as left from the departure station, but were already arrived at the next intermediate station. In case a train has arrived at an intermediate station, it is automatically marked as left from the departure station.
Example incorrect data:
```
<connections version="1.1" timestamp="1596193821">
<connection id="0">
<departure delay="0" canceled="0" left="0" walking="0">
<station locationX="4.672188" locationY="50.90353" id="BE.NMBS.008811288" URI="http://irail.be/stations/NMBS/008811288" standardname="Herent">Herent</station>
<time formatted="2020-07-31T12:58:00">1596193080</time>
<vehicle>BE.NMBS.S93284</vehicle>
<platform normal="1">1</platform>
<stops number="4">
<stop id="0" arrived="1" left="0" …
```
> Ensure the arrived/left data for intermediate stops is sane #348

- tests/integration/VehicleIntegrationTest.php
Travis-CI cron jobs fali every now and then due to a train not driving on weekends. We still want to check this train on weekdays, so added a check to only test the S train on weekdays.
> Fix unstable integration tests due to certain trains not driving on weekends

- src/api/data/NMBS/tools/HafasCommon.php
- tests/integration/VehicleIntegrationTest.php
Clear error message for error code problems, caused by an invalid date parameter in liveboard queries. Fixes #392
> Add clear error message when making a liveboard query with an invalid date, fixes #392

- tests/integration/ConnectionsIntegrationTest.php
- tests/integration/DisturbancesIntegrationTest.php
- tests/integration/LiveboardIntegrationTest.php
- tests/integration/StationsIntegrationTest.php
- tests/integration/VehicleIntegrationTest.php
This PR adds tests to ensure that bugs such as the one described in #423 don't happen again
> Add tests to ensure the XML root elements are always correct. Fixes #423

- src/api/data/NMBS/DisturbancesDatasource.php
The disturbances endpoint will no longer remove anchor tags from disturbance descriptions
Closes #407
> Removed stripping of <a> tags from disturbances end point for descriptions

- composer.json
- src/api/data/NMBS/ConnectionsDatasource.php
- src/api/output/Printer.php
- tests/unit/api/data/NMBS/ConnectionsDatasourceTest.php
- tests/unit/api/data/NMBS/fixtures/connections-issue434.json
- Fixes #434 
- Fixes empty arrays being printed as a `"empty":, ""` in json or `<empty/>` in xml. Now the array is printed exactly like a normal array, but without child elements. For example `<stops number="0"/>`
> Merge development to master, fix #434

- src/api/data/NMBS/CompositionDataSource.php
Hello 👋  
Reading source code, I realized this check was probably a copy-paste mistake as it didn't match the comment right above it.
I just discovered iRail after trying to use the realtime GTFS data of the SNCB/NMBS and missing the composition data. Thanks for the API and for making it open-source 🙏
> Fix subtype decoding for 4 carriages trains

- src/api/data/NMBS/CompositionDataSource.php
The parsed HTML code from Trainmap does not contains a space after the comma anymore.
This commit and the previous one highlight the fragility of the token parsing method, that can break on any formatting update from Trainmap. A more long-lasting solution or a laxer regex may be needed.
Fixes #487
> Fix Trainmap token parsing
