api/APICall.php
api/connections.php
api/data/MIVB/liveboard.php
api/data/MIVB/stations.php
api/data/NMBS/connections.php
api/data/NMBS/liveboard.php
api/data/NMBS/stations.php

The `or` operator does not have the same precedence as `||`. This could
lead to unexpected behavior, use `||` instead.

replace or with ||

---

api/APICall.php
api/connections.php
api/data/DL/tools.php
api/data/MIVB/liveboard.php
api/data/MIVB/stations.php
api/data/NMBS/connections.php
api/data/NMBS/liveboard.php
api/data/NMBS/stations.php
api/data/NS/liveboard.php
api/data/NS/stations.php

Class names should be declared in StudlyCaps. 
You should rename this class to comply with PSR-1.

Studlycaps for file classes. 

---

.gitignore
api/APICall.php
api/data/DL/tools.php
api/data/DataRoot.php
api/data/MIVB/liveboard.php
api/data/MIVB/stations.php
api/data/NMBS/connections.php
api/data/NMBS/liveboard.php
api/data/NMBS/stations.php
api/data/NMBS/tools.php
api/data/NMBS/vehicleinformation.php
api/data/NS/liveboard.php
api/data/NS/stations.php
api/output/Json.php
api/output/Jsonp.php
api/output/Kml.php
api/output/Printer.php
api/output/Xml.php
api/requests/ConnectionsRequest.php
api/requests/LiveboardRequest.php
api/requests/Request.php
api/requests/VehicleinformationRequest.php
composer.lock
includes/simple_html_dom.php

Add a docblock to every function.

add docblock to every function.

---

api/APICall.php
api/connections.php
api/data/DL/tools.php
api/data/MIVB/liveboard.php
api/data/MIVB/stations.php
api/data/NMBS/connections.php
api/data/NMBS/liveboard.php
api/data/NMBS/stations.php
api/data/NS/liveboard.php
api/data/NS/stations.php
api/stats/general.php

Removed deprecated <font> Attribute and the color=“” one in td.
the color attribute i changed it with css classes

remove old html attributes

---

api/stats/api_stats.css

I did a small optimization on the css

optimize css

---

404.html

set the inline css into a css class.

inline css is not done.

---

api/requests/ConnectionsRequest.php
api/requests/LiveboardRequest.php
api/requests/Request.php
api/requests/StationsRequest.php
api/requests/VehicleinformationRequest.php

Reformatted the code. And give a visibility attribute to a couple functions. The request directory is affected with this

reformat code

---

api/output/Json.php
api/output/Jsonp.php
api/output/Kml.php
api/output/Printer.php
api/output/Xml.php

Changelog:
- reformatted code
- added @return attributes to the docblocks.
- add visibility before the functions
Note: I a step forwards to PSR-2. referenced to #101

Improve output directory files.

---

api/data/NMBS/stations.php
api/data/NMBS/tools.php
api/data/NMBS/vehicleinformation.php

i ran code sniffer against the repo. And i found alot of issues. So here is a list from issues that i fixed.
- **api/data/NMBS/stations.php**
- `PSR-2`: add space to if statement. `if(){` -> `if () {`
- `PSR-2`: No space found after comma in function call.
- `PSR-2`: Expected 0 spaces before opening parenthesis; 1 found.
- `PSR-2`: Fix: Expected 1 space between comma and argument  "$request". 0 found.
- `PSR-2`: Usage of ELSE IF is discouraged; use ELSEIF instead.
- `PSR-2`: Expected 1 space after FOREACH keyword; 0 found.
- `PSR-2`: Opening brace should be on a new line. 
- **api/data/NMBS/stations.php** 
- `PSR-2`: Expected 1 space after closing brace; 0 found
- `PSR-2`: Expected 1 space after ELSE keyword; 0 found.
- `PSR-2`: Expected 1 space after IF keyword; 0 found.
- …

PSR-2 Fixes:

---

api/data/NMBS/vehicleinformation.php

This PR contains code that fixes trains that split like L1995, IC716 etc.
To make some trains work, you'll need the latest version from iRail/stations. What do you prefer: a new composer.json that fetches latest version from Github or will you update the packagist version?

Trainsplitters fix

---

api/data/DataRoot.php
api/data/NMBS/vehicleinformation.php

Better error message when no result + parse station ID from URL

---

api/APICall.php
api/data/NMBS/vehicleinformation.php
api/data/structs.php

- Added platform per stop
- Added station id to `stop`, even if `fast=true`

Vehicle information improvements

---

api/data/NMBS/vehicleinformation.php

Fix for missing delay/canceled info on last stop

---

api/data/NMBS/connections.php
api/data/NMBS/liveboard.php
api/data/NMBS/vehicleinformation.php
api/output/Xml.php

<![CDATA[ in XML

---

api/data/NMBS/connections.php
api/data/NMBS/vehicleinformation.php

Fixed various issues related to delay and canceled

---

api/data/NMBS/connections.php

Update connections.php for IS_ALTERNATIVE

---

api/data/NMBS/connections.php

in parseHafasXml:
added via->departPlatformNormal
added via->arrivalPlatformNormal
added via->arrivalDelay
added via->departDelay

in vias, added platformNormal and delay

---

api/APICall.php
api/data/NMBS/connections.php
api/data/NMBS/liveboard.php
api/data/NMBS/stations.php
api/requests/ConnectionsRequest.php
api/requests/LiveboardRequest.php

Advancing the logs

---

api/logs.php

Thank you @serkanyildiz for the report!

Hot fix for cache header and cross origin header

---

composer.json
composer.lock

The installation process is fixed. A dependency is added which makes sure the 'composer install' command works.

Composer install is fixed

---

api/data/NMBS/vehicleinformation.php
api/logs.php
api/output/Xml.php

Fix for 1 vehicle issue

---

.gitignore
README.md
api/.env.example
api/APIPost.php
api/spitsgids/OccupancyOperations.php
api/spitsgids/SpitsgidsController.php
composer.json
composer.lock

Fixed the two last checkboxes in this pull request: https://github.com/iRail/iRail/pull/191.

Enviroment config file and validation occupancy URI

---

api/data/DataRoot.php

change it with suggesting to open an issue
fixes #163

don't display email address in error message

---

api/data/NMBS/connections.php
api/data/NMBS/liveboard.php
api/data/NMBS/vehicleinformation.php

Issue https://github.com/iRail/iRail/issues/219 should be fixed by this.

Added the departureConnection URI to each GET request

---

README.md
api/data/NMBS/vehicleinformation.php

Made sure that occupancy is also returned if BE.NMBS prefix in parameter in vehicle GET request is left out.

Give correct occupancy for each id parameter in vehicle GET request

---

api/.htaccess
api/APIPost.php
api/data/NMBS/connections.php
api/data/NMBS/liveboard.php
api/data/NMBS/stations.php
api/data/NMBS/vehicleinformation.php
api/feedback/occupancy.php
api/occupancy/OccupancyDao.php
api/occupancy/OccupancyOperations.php

CORS and warnings fixed

---

api/terms/index.html
api/terms/unknown.html

fixes #250 
Also adds RDFa to `unknown`.
Does the index need `label`/`comment` RDFa tags?
There should also be styling here, I'll check what ones I can reuse.

Add a terms overview/index page

---

api/data/NMBS/vehicleinformation.php
api/data/structs.php
api/output/Xml.php

- Semantic vehicle id
- Vehicle location now points to last station
- Vehicle shortname (IC1234) and name (BE.NMBS.IC1234)
#307

Vehicle endpoint improvements and fixes

---

api/data/NMBS/connections.php
api/data/NMBS/disturbances.php
api/data/NMBS/liveboard.php
api/data/NMBS/stations.php
api/data/NMBS/tools.php
api/data/NMBS/vehicleinformation.php
api/output/Xml.php

This PR adds 
- a new liveboard source which should be more reliable and change less
- disturbances endpoint will stay online even if NMBS site goes offline for less than one hour. #326 
The new liveboard source still requires thorough validation before this is merged to master.

New liveboard source, disturbances while NMBS offline

---

README.md

Updated readme to reflect mongo being included by default.

Update readme for better installation instructions

---

api/data/NMBS/connections.php
api/data/NMBS/liveboard.php
api/data/NMBS/stations.php
api/data/structs.php
api/requests/ConnectionsRequest.php
composer.json

Issue #356  is quite urgent to be fixed. Tested on staging!

Fix for #356

---

api/data/NMBS/connections.php
api/data/NMBS/liveboard.php
api/data/NMBS/stations.php
api/data/structs.php
api/output/Printer.php

Fixes for #365 and #363 , altered fix for #356 .
Can merge when those three issues has been verified as fixed.
- Variables starting with priv__ are not serialized
- Fixed binary vehicle selection strings for connections endpoint

Bugfixes for serialisation and vehicle selection

---

api/data/NMBS/disturbances.php

Implements #370, a new data field which links to the attachment (when available) for disturbances, as well as small improvements for printing out the text. Requires validation in staging to check if this doesn't break existing applications.

Support attachments for disturbances

---

api/data/NMBS/connections.php

Use the new dInR and aOutR fields to parse the arrived/left state of trains

---

README.md
api/data/NMBS/tools.php
composer.json
docker-compose.yml
docker/nginx/Dockerfile
docker/nginx/default.conf
docker/php/Dockerfile
docker/php/crontab

Hi my friend here is all section you what about https://github.com/iRail/iRail/issues/386, if have any comment please tell me

resolving Issue #386 dockrize the project

---

.gitignore

add `docker/nginx/logs` folder to .gitignore

Issue386(add nginx logs file to .gitignore)

---

api/data/NMBS/Connections.php
api/data/NMBS/Liveboard.php
api/data/NMBS/Stations.php
api/data/structs.php
api/output/Printer.php
composer.json

Bugfixes #397 #398

---

api/data/NMBS/Connections.php

Intermediate stops should be nested in the via departure; not the via itself #348

Bugfix for intermediary stops

---

api/data/NMBS/Connections.php
api/output/Xml.php

This pull requests ensures that <title> elements make use of CDATA for their contents, to prevent invalid XML output.

408 fix disturbances xml

---

api/data/DataRoot.php
api/data/NMBS/Connections.php
api/data/NMBS/Liveboard.php
api/data/NMBS/VehicleInformation.php
api/output/Xml.php

Fix special characters in XML #408

---

src/api/data/DataRoot.php
src/api/data/NMBS/StationsDatasource.php
tests/integration/StationsIntegrationTest.php

This PR fixes the empty station list (#418) introduced by #416

Fix stations API endpoint showing an empty list #418

---

src/api/data/DataRoot.php
src/api/data/NMBS/StationsDatasource.php
tests/integration/StationsIntegrationTest.php

Fixes stations API endpoint showing an empty list #418

Deploy of bugfix for stations API endpoint showing an empty list

---

src/api/data/NMBS/CompositionDataSource.php
src/api/data/NMBS/ConnectionsDatasource.php
src/api/data/NMBS/VehicleDatasource.php
tests/integration/VehicleIntegrationTest.php

Fixes train searches by vehicle number, without the train type (e.g. 538 instead of IC538). Adds regression tests. Fixes debug logging which broke due to change file structure.

Fix vehicle search by vehicle number, fix debug logging

---

src/api/data/NMBS/VehicleDatasource.php

Fix alert language for vehicles #443

---

composer.json
src/api/data/NMBS/DisturbancesDatasource.php

Fixes errors being included when NMBS returns invalid data

447 disturbances simplexml fix

---

src/api/data/NMBS/CompositionDataSource.php

Fix Trainmap token parsing and retrieval
